services:
  web:
    image: mahiddandamun/magic-stream-web-prod${IMAGE_TAG:-latest}
    container_name: magic-stream-web-prod
    ports:
      - "8081:80"
    restart: always

  api:
    image: mahiddandamun/magic-stream-api-prod${IMAGE_TAG:-latest}
    container_name: magic-stream-api-prod
    restart: always
