services:
  web:
    # build: ./Client/magic-stream-client
    depends_on:
      - api
    image: magic-stream-web:1.0.0
    container_name: magic-stream-web
    ports:
      - "5173:5173"
    environment:
      - API_URL=http://${API_HOST_IP}:8080

  api:
    # build: ./Server/MagicStreamServer
    depends_on:
      - db
    image: magic-stream-api:1.0.0
    container_name: magic-stream-api
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      SECRET_KEY: "${SECRET_KEY}"
      REFRESH_TOKEN_SECRET: "${REFRESH_TOKEN_SECRET}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      BASE_PROMPT_TEMPLATE: "${BASE_PROMPT_TEMPLATE}"
      RECOMMENDED_MOVIE_LIMIT: "${RECOMMENDED_MOVIE_LIMIT}"
      MONGODB_URI: "${MONGODB_URI}"
      DATABASE_NAME: "${DATABASE_NAME}"
      ALLOWED_ORIGINS: "${ALLOWED_ORIGINS}"
  db:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - movies:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
  seed:
    image: mongo:latest
    container_name: mongo-seed
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./seed:/seed-data
    command: mongosh mongodb://db:27017/magic-stream-movies /seed-data/seed.js
    restart: "no"

volumes:
  movies:
